In [1]:
import numpy as np

In [2]:
a = [1, 2, 3, 4, 5]
print(a)
print(a[1])
print(a[1:4])

[1, 2, 3, 4, 5]
2
[2, 3, 4]


In [3]:
a = np.array([1,2,3,4,5])
print(a)
print(a[1])
print(a[1:4])

[1 2 3 4 5]
2
[2 3 4]


In [4]:
a[2] = 10
print(a)

[ 1  2 10  4  5]


In [5]:
a_mul = np.array([[[1, 2, 3, 1], [4, 5, 6, 1], [7, 8, 9, 1]], [[1, 2, 3, 1], [4, 5, 6, 1], [7, 8, 9, 1]]])
print(a_mul[0])
print(a_mul[0, 1])

[[1 2 3 1]
 [4 5 6 1]
 [7 8 9 1]]
[4 5 6 1]


In [6]:
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

(2, 3, 4)
3
24
int64


In [7]:
a = np.array([[1, 2, 3],
            [4, "5", 6],
            [7, 8, 9]], dtype = np.float32)
print(a.dtype)

float32


In [8]:
print(a[1][1].dtype)
print(type(a[0][0]))
print(a[0, 0])

float32
<class 'numpy.float32'>
1.0


In [9]:
a = np.full((2, 3, 4), 9)
print(a)
print(a.shape)
a = np.zeros((2, 3, 7))
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
(2, 3, 4)
[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]


In [10]:
a = np.empty((5, 5, 5))
print(a)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [59]:
x_values = np.arange(0, 1200, 5)
print(x_values)

[   0    5   10   15   20   25   30   35   40   45   50   55   60   65
   70   75   80   85   90   95  100  105  110  115  120  125  130  135
  140  145  150  155  160  165  170  175  180  185  190  195  200  205
  210  215  220  225  230  235  240  245  250  255  260  265  270  275
  280  285  290  295  300  305  310  315  320  325  330  335  340  345
  350  355  360  365  370  375  380  385  390  395  400  405  410  415
  420  425  430  435  440  445  450  455  460  465  470  475  480  485
  490  495  500  505  510  515  520  525  530  535  540  545  550  555
  560  565  570  575  580  585  590  595  600  605  610  615  620  625
  630  635  640  645  650  655  660  665  670  675  680  685  690  695
  700  705  710  715  720  725  730  735  740  745  750  755  760  765
  770  775  780  785  790  795  800  805  810  815  820  825  830  835
  840  845  850  855  860  865  870  875  880  885  890  895  900  905
  910  915  920  925  930  935  940  945  950  955  960  965  970  975
  980 

In [67]:
a = np.linspace(0, 1000, 1001)
print(a)

[   0.    1.    2. ...  998.  999. 1000.]


In [73]:
print(np.nan)
print(np.inf)
print(type(np.nan))
print(type(np.inf))

nan
inf
<class 'float'>
<class 'float'>


In [75]:
print(np.isnan(np.nan))
print(np.isnan(2))
print(np.isinf(np.inf))
print(np.isinf(5))

True
False
True
False


In [81]:
print(np.isinf(np.array([10]) / 0))

[ True]


C:\Users\Dell\AppData\Local\Temp\ipykernel_30416\3436478471.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10]) / 0))


In [83]:
l1 = [1, 2, 3, 4, 5]
l2 = [6, 7, 8, 9, 0]
a1 = np.array(l1)
a2 = np.array(l2)

In [95]:
print(l1 * 5)
print(a1 * 5)
print(a1 / 5)
print(a1 + l2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[ 7  9 11 13  5]


In [101]:
a1 = np.array([1, 2, 3])
a2 = np.array([[1],
              [2],
              [3]])
print(a1.shape)
print(a2.shape)
print(a1 + a2)

(3,)
(3, 1)
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [105]:
a = np.array([[1, 2, 3],
       [4, 5, 6]])
print(np.sqrt(a))


[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [107]:
print(np.sqrt(a))
print(np.cos(a))
print(np.sin(a))
print(np.tan(a))
print(np.log(a))
print(np.log2(a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
[[0.         1.         1.5849625 ]
 [2.         2.32192809 2.5849625 ]]


In [111]:
a = np.array([1, 2, 3])
a = np.append(a, [7, 8, 9])

In [113]:
print(a)

[1 2 3 7 8 9]


In [117]:
a = np.insert(a, 3, [4, 5, 6])
print(a)

[1 2 3 4 5 6 7 8 9]


In [123]:
a = np.delete(a, 1)
print(a)

[1 4 5 6 7 8 9]


In [143]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(np.delete(a, 2, 1))

[[1 2]
 [4 5]]


In [171]:
a = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10],
             [11, 12, 13, 14, 15],
             [16, 17, 18, 19, 20]])

print(a.shape)
print(a.reshape((5, 4)))
print(a.reshape(20,))
print(a.reshape(10, 2))
print(a.reshape(5, 2, 2))

(4, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


In [179]:
print(a)
a.reshape(5, 4)
print(a)
a.resize(5, 4)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [183]:
print(a.flatten())
print(a.ravel())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [187]:
var1 = a.flatten()
var1[2] = 100
print(var1)
print(a)

var1 = a.ravel()
var1[2] = 100
print(var1)
print(a)

[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[  1   2 100   4]
 [  5   6   7   8]
 [  9  10  11  12]
 [ 13  14  15  16]
 [ 17  18  19  20]]


In [191]:
var = [v for v in a.flat]
print(var)

[np.int64(1), np.int64(2), np.int64(100), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]


In [199]:
print(a.transpose())
print(a.T)
print(a.swapaxes(0, 1))

[[  1   5   9  13  17]
 [  2   6  10  14  18]
 [100   7  11  15  19]
 [  4   8  12  16  20]]
[[  1   5   9  13  17]
 [  2   6  10  14  18]
 [100   7  11  15  19]
 [  4   8  12  16  20]]
[[  1   5   9  13  17]
 [  2   6  10  14  18]
 [100   7  11  15  19]
 [  4   8  12  16  20]]


In [203]:
a = np.array([[1, 2, 3, 4, 5],
             [6, 7, 8, 9, 10]])

b = np.array([[11, 12, 13, 14, 15],
             [16, 17, 18, 19, 20]])

In [237]:
ab = np.concatenate((a, b), axis=0)
print(ab)

print(a.shape)
print(b.shape)
ab = np.stack((a, b))

ab = np.vstack((a, b))
print(ab)
ab = np.hstack((a, b))
print(ab)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(2, 5)
(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [265]:
print(np.split(ab, 5, axis = 1))

[array([[1, 2],
       [6, 7]]), array([[3, 4],
       [8, 9]]), array([[ 5, 11],
       [10, 16]]), array([[12, 13],
       [17, 18]]), array([[14, 15],
       [19, 20]])]


In [267]:
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())
print(np.median(a))

1
10
5.5
2.8722813232690143
55
5.5


In [295]:
numbers = np.random.randint(0, 100, size=(2, 3, 5))
print(numbers)

[[[38 98 53 94 44]
  [74 29 78 88 92]
  [21 37  7 34 37]]

 [[49 90 96 13 58]
  [91 90 67 68 44]
  [18 26  2 93 99]]]


In [303]:
numbers = np.random.binomial(10, p=0.5, size=(5
                                              , 5, 10))
print(numbers)

[[[ 5  6  6  6  8  7  6  9  5  6]
  [ 3  5  5  7  5  3  3  4  5  7]
  [ 6  4  5  5  4  4  7  5  5  7]
  [ 4  6  6 10  6  8  6  5  4  2]
  [ 5  5  5  5  6  3  8  6  6  4]]

 [[ 6  5  5  5  5  6  4  7  5  7]
  [ 6  6  5  1  6  2  4  5  6  7]
  [ 7  5  6  5  4  6  3  5  7  6]
  [ 6  6  4  4  6  5  5  6  5  5]
  [ 7  5  5  5  4  4  5  5  6  5]]

 [[ 9  5  3  8  3  6  6  5  6  4]
  [ 5  5  7  6  4  8  7  1  4  4]
  [ 3  5  3  3  6  4  5  4  4  6]
  [ 5  9  5  6  7  5  5  6  4  8]
  [ 6  5  6  3  3  5  2  7  4  5]]

 [[ 5  3  3  3  8  5  4  8  3  7]
  [ 3  5  5  5  4  6  5  4  5  4]
  [ 7  4  7  4  4  7  4  5  5  6]
  [ 5  8  7  7  3  2  5  5  6  4]
  [ 5  3  4  5  5  7  4  4  5  6]]

 [[ 5  6  2  3  4  6  5  6  3  4]
  [ 6  8  4  5  4  4  7  7  5  5]
  [ 5  7  6  3  5  6  5  5  6  5]
  [ 3  4  6  5  4  5  6  5  2  3]
  [ 8  7  5  4  6  5  4  4  5  3]]]


In [309]:
numbers = np.random.normal(loc=170, scale=15, size=(5, 10))
print(numbers)

[[169.26842309 145.49843528 171.02646647 169.03493156 142.14550245
  178.03501296 174.61532117 153.73421039 172.71989099 161.97619675]
 [159.54529465 161.79606467 169.14702557 170.30162047 149.75808629
  152.8582114  188.60646157 153.29559397 164.28402549 174.49480344]
 [177.03325991 171.40862119 189.82778012 145.40990683 145.09554317
  169.66446589 173.41223947 168.28795564 176.23973924 168.04770642]
 [162.75543229 173.58153695 152.05721689 156.32842774 148.77156715
  188.20984859 163.89239911 172.23448844 169.78052764 159.79921319]
 [175.3067686  163.32092959 187.85571531 195.71210248 182.73578182
  136.43854364 177.9540663  188.10199396 162.0765824  164.47884779]]


In [317]:
numbers = np.random.choice([1, 2, 3, 4], size=(2,3))
print(numbers)

[[4 3 1]
 [2 1 1]]


In [323]:
np.save("Downloads/myarray.npy", numbers)

In [325]:
a = np.load("Downloads/myarray.npy")
print(a)

[[4 3 1]
 [2 1 1]]


In [327]:
np.savetxt("Downloads/myarray.csv", numbers, delimiter=",")

In [333]:
a = np.loadtxt("Downloads/myarray.csv", delimiter=",")
print(a)

[[4. 3. 1.]
 [2. 1. 1.]]
